name: fleet_management_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jsonschema=4.23.0
  - pip=24.2
  - python=3.12.0
  - sortedcontainers=2.4.0
  - pip:
      - paho-mqtt==2.1.0
      - pygame==2.6.1
      - pygame-screen-record==0.1.1
